# Generated by Django 2.2.28 on 2025-02-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campusonline", "0078_linz"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailmanServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "student_domain",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "personal_domain",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mailinglist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                ("domain", models.CharField(blank=True, max_length=1024, null=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "moderators",
                    models.ManyToManyField(
                        db_constraint=False,
                        null=True,
                        related_name="_mailinglist_moderators_+",
                        to="campusonline.Person",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campusonline.Organization",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailinglist.MailmanServer",
                    ),
                ),
            ],
        ),
    ]
