# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0079_alter_event_options"),
        ("mailinglist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="moderators",
            field=models.ManyToManyField(
                db_constraint=False, related_name="+", to="campusonline.person"
            ),
        ),
    ]
