from appconf import AppConf
from django.conf import settings


class MailinglistAppConf(AppConf):
    STUDENT_LIST = "students"
    PERSONAL_LIST = "personal"
    LIST_STYLE = "legacy-announce"
    LIST_SETTINGS = {
        "acceptable_aliases": [],
        "accept_these_nonmembers": [],
        "admin_immed_notify": True,
        "admin_notify_mchanges": False,
        "administrivia": True,
        "advertised": False,
        "allow_list_posts": False,
        "anonymous_list": True,
        "archive_policy": "never",
        "archive_rendering_mode": "text",
        "autorespond_owner": "none",
        "autorespond_postings": "none",
        "autorespond_requests": "none",
        "autoresponse_grace_period": "90d",
        "autoresponse_owner_text": "",
        "autoresponse_postings_text": "",
        "autoresponse_request_text": "",
        "bounce_info_stale_after": "7d",
        "bounce_notify_owner_on_disable": True,
        "bounce_notify_owner_on_removal": True,
        "bounce_score_threshold": 5,
        "bounce_you_are_disabled_warnings": 3,
        "bounce_you_are_disabled_warnings_interval": "7d",
        "collapse_alternatives": True,
        "convert_html_to_plaintext": False,
        "default_member_action": "hold",
        "default_nonmember_action": "hold",
        "digest_send_periodic": True,
        "digest_size_threshold": 30.0,
        "digest_volume_frequency": "monthly",
        "digests_enabled": False,
        "discard_these_nonmembers": [],
        "dmarc_mitigate_action": "no_mitigation",
        "dmarc_mitigate_unconditionally": False,
        "dmarc_moderation_notice": "",
        "dmarc_wrapped_message_text": "",
        "emergency": False,
        "filter_action": "discard",
        "filter_content": False,
        "filter_extensions": [],
        "filter_types": [],
        "first_strip_reply_to": False,
        "forward_unrecognized_bounces_to": "administrators",
        "gateway_to_mail": False,
        "gateway_to_news": False,
        "hold_these_nonmembers": [],
        "include_rfc2369_headers": True,
        "info": "DO NOT MODIFY!",
        "linked_newsgroup": "",
        "max_message_size": 0,
        "max_num_recipients": 10,
        "max_days_to_hold": 0,
        "member_roster_visibility": "moderators",
        "moderator_password": None,
        "newsgroup_moderation": "none",
        "nntp_prefix_subject_too": True,
        "pass_types": [],
        "pass_extensions": [],
        "personalize": "none",
        "posting_pipeline": "default-posting-pipeline",
        "preferred_language": "de",
        "process_bounces": True,
        "reject_these_nonmembers": [],
        "reply_goes_to_list": "no_munging",
        "reply_to_address": "",
        "require_explicit_destination": True,
        "respond_to_post_requests": True,
        "send_goodbye_message": False,
        "send_welcome_message": False,
        "subject_prefix": "",
        "subscription_policy": "moderate",
        "unsubscription_policy": "confirm",
        "usenet_watermark": None,
    }

    class Meta:
        prefix = "mailinglist"
